[package]
name = "blockchain"
version = "0.1.0"
authors = ["Jose Luis Manriquez <jose.manriquez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-hash = "0.3.4"
clap = "2.33.0"
router = "0.6.*"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"